on:
  schedule:
    - cron: 00 17 * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate and add plots
        run: |
          python main.py
          git add next_collection_date.json
