name: Send daily
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: 00 17 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main and add next_collection_date
      run: |
        python main.py
        git add next_collection_date.json
